version: '3.8'

services:
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: barat
      POSTGRES_PASSWORD: barat1378
      POSTGRES_DB: trello_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

volumes:
  postgres_data:


