server:
  host: "localhost"
  port: 3000

database:
  host: "localhost"
  port: 5432
  username: "barat"
  password: "barat1378"
  name: "trello_db"

logging:
  level: "info"
  format: "json"

jwt:
  secret_key: "trello"
  expiration_minutes: 60

roles:
  admin: "Admin"
  user: "Standard User"

status:
  completed: "Completed"
  progress: "In Progress"
  planned: "Planned"

features:
  enable_feature_x: true
  enable_feature_y: false
